[package]

name = "doc"
version = "0.0.23" #auto
authors = [ "SiegeLord <slabode@aim.com>" ]

[lib]
name = "delete_me"
path = "dummy.rs"

[dependencies.gnuplot]

path = ".."
version = "=0.0.23" #auto
